services:
  jobmanager:
    image: flink-python
    build: .
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./:/opt/flink/work  # Map current directory to work directory
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink-python
    build: .
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./:/opt/flink/work  # Same mapping for taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2