apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: flink
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.memory.process.size: 1600m
    jobmanager.memory.flink.size: 1024m
    jobmanager.memory.heap.size: 1024m
    taskmanager.numberOfTaskSlots: 2
    taskmanager.memory.process.size: 2048m
    parallelism.default: 4
    kubernetes.container.image: flink:1.18.0-java11
    kubernetes.namespace: flink
    
    # Explicitly bind to all interfaces
    jobmanager.bind-host: 0.0.0.0
    taskmanager.bind-host: 0.0.0.0
    blob.server.bind-host: 0.0.0.0
    rest.bind-address: 0.0.0.0  
    
    # Set explicit ports
    jobmanager.rpc.port: 6123
    blob.server.port: 6124
    taskmanager.rpc.port: 6122
    rest.bind-port: 8081
    
    # Extended timeouts
    blob.client.connect.timeout: 120000
    blob.client.socket.timeout: 300000
    
    # Debug logging
    logger.org.apache.flink.runtime.blob.level: DEBUG
    logger.org.apache.flink.runtime.rpc.level: DEBUG
    
    kubernetes.container.image: flink:1.18.0-java11
    kubernetes.namespace: flink
  log4j-console.properties: |
    # Root logger
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    rootLogger.appenderRef.file.ref = FileAppender
    
    # Console appender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    
    # File appender
    appender.file.name = FileAppender
    appender.file.type = FILE
    appender.file.fileName = ${sys:log.file}
    appender.file.layout.type = PatternLayout
    appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n