apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
      - name: job-artifacts
        persistentVolumeClaim:
          claimName: flink-job-artifacts
      - name: eventhubs-config
        configMap:
          name: eventhubs-config
      containers:
      - name: jobmanager
        image: flink:1.18.0-java11
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: job-artifacts
          mountPath: /opt/flink/usrlib
        - name: eventhubs-config
          mountPath: /opt/flink/conf/eventhubs
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        - name: AZURE_BLOBSTORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: trend-detection
              key: AZURE_BLOBSTORAGE_CONNECTION_STRING
        - name: AZURE_EVENTHUB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: trend-detection
              key: AZURE_EVENTHUB_CONNECTION_STRING
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: trend-detection
              key: AZURE_OPENAI_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "4"
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: rpc
    port: 6123
    targetPort: 6123
  - name: blob
    port: 6124
    targetPort: 6124
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-ui
  namespace: flink
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: flink
    component: jobmanager