apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: job-artifacts
        persistentVolumeClaim:
          claimName: flink-job-artifacts
      - name: embedding-socket
        emptyDir: {}
      initContainers:
      - name: socket-setup
        image: busybox
        command: ["sh", "-c", "mkdir -p /tmp/sockets && chmod 777 /tmp/sockets"]
        volumeMounts:
        - name: embedding-socket
          mountPath: /tmp/sockets
      containers:
      - name: taskmanager
        image: flink:1.18.0-java11
        args: ["taskmanager"]
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: job-artifacts
          mountPath: /opt/flink/usrlib
        - name: embedding-socket
          mountPath: /tmp
        env:
        - name: SOCKET_PATH
          value: "/tmp/embedding_server.sock"
      - name: embedding-server
        image: krinart.azurecr.io/embedding-server:latest
        volumeMounts:
        - name: embedding-socket
          mountPath: /tmp
        env:
        - name: SOCKET_PATH
          value: "/tmp/embedding_server.sock"
        resources:
          limits:
            cpu: "4"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"