FROM python:3.9-slim

WORKDIR /app

# Install required packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Python server code
COPY server.py .

# Run the server
CMD ["python", "server.py"]